# Generated by Django 4.1.4 on 2022-12-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_rename_historicalprices_historicalprice_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="historicalprice",
            constraint=models.UniqueConstraint(
                fields=("stock", "timestamp"), name="dated_price"
            ),
        ),
    ]
