# Generated by Django 4.1.4 on 2022-12-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_historicalprice_dated_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprice',
            options={'ordering': ['stock', '-datetime']},
        ),
    ]
