# Generated by Django 4.1.4 on 2022-12-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_stock_lower_limit_stock_upper_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.portfolio'),
        ),
    ]
