# Generated by Django 4.1.4 on 2022-12-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_portfolio_stock_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
