# Generated by Django 4.1.4 on 2022-12-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.portfolio'),
        ),
    ]
